
name: Full Stack CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20]

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # -------------------- FRONTEND --------------------
     

      - name: Install Frontend Dependencies
        run: |
          pwd && ls -la
          cd frontend
          npm ci --force --verbose
      - name: Build Frontend
        run: |
          cd frontend
          npm run build --verbose
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm test -- --verbose
      # -------------------- BACKEND --------------------
      - name: Use Node.js ${{ matrix.node-version }} (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci --force --verbose
      - name: Run Backend Tests
        run: |
          cd backend
          npm test -- --verbose
