name: Full Stack CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:

  # ===================== FRONTEND JOB =====================
  frontend-build:
    name: Frontend Build
    runs-on: [self-hosted]     # Runner 1
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci --force --verbose

      - name: Build Frontend
        run: |
          cd frontend
          npm run build --verbose


  # ===================== BACKEND JOB =====================
  backend-build:
    name: Backend Build
    runs-on: [self-hosted]      # Runner 2
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci --force --verbose

       - name: Run Backend
       run: |
            cd backend
            num start  --verbose
